import { ClerkProvider } from '@clerk/nextjs'
import './globals.css'
import type { Metadata } from 'next'
import { Asap } from 'next/font/google'
// import { ThemeProvider } from '@/components/provider/theme-provider'
import { cn } from '@/lib/utils'

const font = Asap({ weight: ['600'],preload: false, })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={cn(font.className, 'bg-white dark:bg-[#313338]')}>
          {/* <ThemeProvider attribute='class' defaultTheme='dark' enableSystem={false} storageKey='chat-theme'></ThemeProvider> */}
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
